step1: cyoa-step1.cpp
	g++ -o step1 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step1.cpp
 
step2: cyoa-step2.cpp
	g++ -o step2 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step2.cpp 

step4: cyoa-step4.cpp
	g++ -o step4 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step4.cpp 
