step1: cyoa-step1.cpp cyoa.h
	g++ -o step1 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step1.cpp
 
step2: cyoa-step2.cpp cyoa.h
	g++ -o step2 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step2.cpp
 
step3: cyoa-step3.cpp cyoa.h
	g++ -o step3 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step3.cpp  

step4: cyoa-step4.cpp cyoa.h
	g++ -o step4 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step4.cpp 
